### ISSUE TITLE
navbar avatar visible even when logged out

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#248]
**Describe the bug**
the navbar avatar is visible even when logged out and on landing page. It does force the user to login again if they try to use the dropdown but it shouldn't be there in the first place.

**To Reproduce**
I believe this only starts occurring when keycloak session times out but the application thinks you are still logged in

**Expected behavior**
If you are not logged in it should say "sign in"  instead of avatar

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/81968065-dfa0d700-95e9-11ea-8b16-a60a3036981f.png)

![image](https://user-images.githubusercontent.com/11470442/81968097-efb8b680-95e9-11ea-8a14-5dff3c382bf9.png)

**Additional context**

**Comment by BenJeau** [comment]
Just thought of this, I think an easy way to do this is to try to init keycloak in LandingPage, and update the redux user values accordingly

**Comment by BenJeau** [comment]
I'm able to reproduce the issue locally with the latest dev, when I got timed out. I think what we just need to do (since we now know if the user is not authenticated because of the new keycloak update from @MohamedRadwan) is to clear the redux store if they are not authenticated. Should be an easy fix, will open a PR soon
