### ISSUE TITLE
Fuzzy search populates search sidebar incorrectly

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#270]
**Describe the bug**
When using the main search bar the side bar on the search results page shows "[object object]" for the name field

**To Reproduce**
1. Go to '/secured/home'
2. type "ali" in main search field
3. click search
4. See [object object] in side bar

**Expected behavior**
It should just avoid auto filling in the form if the general search field is used

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/82382490-0ef48100-99fa-11ea-8028-ee9a68910c6f.png)

**Comment by BenJeau** [comment]
`[object Object]` is present in the field name since the placeholder for Input cannot receive a ReactNode for some reason, changing the placeholder to text fixes the problem, it's not related with the pre-population from the queryString. Right now the searchValue from the queryString is not used in that sidebar component

**Comment by BenJeau** [comment]
![image](https://user-images.githubusercontent.com/22248828/82384905-e1f69d00-99fe-11ea-818a-373b7507368b.png)

**Comment by dynamic11** [comment]
will update #272 to fix this issue
