### ISSUE TITLE
On the Results Page, make the results card larger and same size

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#294]
The current cards are small and in different sizes

![image](https://user-images.githubusercontent.com/49656364/82836765-35506b80-9e95-11ea-8dc7-f81366c7300c.png)

**Comment by BenJeau** [comment]
I'd like to start a conversation on potentially have the cards be rows, so that the user will only search vertically (like facebook and linkedin) instead of vertically and horizontally for a profile.

__Examples:__
![image](https://user-images.githubusercontent.com/22248828/82939790-d3116c80-9f61-11ea-9bc7-0cdf940ab6d2.png)
![image](https://user-images.githubusercontent.com/22248828/82939898-005e1a80-9f62-11ea-97d1-5856479c24a1.png)

It would make the results page less "cramped" while being more readable and less shocking for the user (when seeing a lot of information).

What do you think? @KateAThornley @dynamic11

**Comment by dynamic11** [comment]
**just to add to the discussion:**

this was the original mock-up
![image](https://user-images.githubusercontent.com/11470442/82940323-a578f300-9f62-11ea-9df1-0aa00b7e0675.png)

**Comment by MenaMachado** [comment]
You can continue to provide comments, but I need to give this more thought before we making any design decisions.

**Comment by BenJeau** [comment]
What are your thoughts on making it a single column? If we want multiple columns, I would put it at a max of two, but personally, I would only have one. @dynamic11 @KateAThornley

**Comment by MenaMachado** [comment]
I agree Let’s go with one row.

We need to think about what we want to display from the profiles.

On Jun 1, 2020, at 3:01 PM, Benoît Jeaurond <notifications@github.com> wrote:

﻿

What are your thoughts on making it a single column? If we want multiple columns, I would put it at a max of two, but personally, I would only have one. @dynamic11<https://github.com/dynamic11> @KateAThornley<https://github.com/KateAThornley>

**Comment by BenJeau** [comment]
![image](https://user-images.githubusercontent.com/22248828/87334807-399c1b00-c50d-11ea-80a1-1459d03f6dc8.png)
