### ISSUE TITLE
Geds API unable to fetch data

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#319]
**Describe the bug**
When creating a new account the GEDS API fails to fetch user data
**To Reproduce**
1. Delete your database
2. Create a new account

**Comment by mo-5** [comment]
I have been thinking about this and wanted to write the comment before I forgot. @BenJeau  shouldn't this API call happen in the frontend? I don't see the point of making it the call from the server then sending it to the frontend. This will just make the call slower and increase the chances of errors. I think instead of making the call to our backend we should make it directly to GEDS from the frontend.  What's your opinion on this?

**Comment by dynamic11** [comment]
From what I remember (please correct me if I’m wrong) they way it currently works is:
Front end requests geds profile from backend->backend uses geds API and gets info returns info to front end->front end uses info to auto fill the form and once user saves its sends data back to backend to save profile.

Here are my thoughts:
- Ideally we want the backend to just get the geds API info and create profile automatically and the front end just fetches the profile from db to auto fill the forms. This will simplify the amount of transactions 
- this will simplifying it but doing the above method cause one future problem. If we want to implement “update profile from geds” in “edit profile” we would probably want the front end to show a diff to the user of the information that will be changed if they choose to continue with the update. Now if we want to generate this “diff” on the front end we will need to keep our backend the way it is now so that it just sends Geds API results. If we want to do the “diff” in the backend and just sent the “diffed” data to front end then we should implement the above idea and just create a new endpoint. 
- my general opinion is that the geds API should be done in the backend since i prefer the front end only contacting one server for the sake of simplicity.

Let me know what you guys think or if my explanation was unclear. I’m on my phone so it’s harder to format/type.

**Comment by BenJeau** [comment]
If the api call for geds doesn't need an api key, then it could be made directly in the frontend, but I think we should only query one "api", aka our backend for the app. @dynamic11 what are your thoughts on this?

**Comment by dynamic11** [comment]
Wow we just commented at same time. I can read your mind @BenJeau
