### ISSUE TITLE
Create an "About I-Talent" page

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#444]
**Is your feature request related to a problem? Please describe.**
Some users may not know what I-Talent is or is used for.

**Describe the solution you'd like**
When users are unclear about the purpose of I-Talent, they should be able to find a FAQ or About page in the footer of the site that will give them context to the app. It should include a mission statement, a simple guide on how to use I-Talent, an FAQ section, and a section to report further issues/questions not answered via our FAQ.

**Comment by dynamic11** [comment]
I was thinking about this and wanted to see what you guys (@MenaMachado and @KateAThornley) think about creating this documentation in a wiki service like Confluence❓❓❓ 

**Advantage of using Confluence:**
- department standard
- easy to maintain and update by HR or another non technical person
- reduces our code base size
- minimizes the number of pages that need to be maintained in the app
- much faster/easier to make than hard coding all the content and styling it

**Advantage of building it into app:**
- it can be hard to style/make Confluence look pretty
- user will have to leave the app to access the documentation
- we are limited to Confluence features

We can use another wiki product, but because confluence is standard I though we should consider that first.

Let me know what you think 😃

**Comment by KateAThornley** [comment]
> Confluence

I've been looking into Confluence over the weekend and I think it might be a really good route to take because of how much easier it would be for our client to keep the documentation up to date, and it would relieve the work of a future dev of going into our code everytime an FAQ page needs to be updated. The system organization seems to be simple/manageable as well (see image). We could use it with Jira to report bugs potentially I think. 
![image](https://user-images.githubusercontent.com/43188335/86551108-2c31d000-bf12-11ea-80a9-3dd41bc4ddab.png)

In terms of styling dificulties, I've been reading that all you need to do is paste in your css into the custom styles box but I'm not sure how reliable it'll be.

It should also be considered that its about 10 dollars a month per user.

@MenaMachado what do you think about this as an alternative to the in-app page we discussed on Friday?
