### ISSUE TITLE
Friends should be called "Private group"

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#484]
**Is your feature request related to a problem? Please describe.**
It just makes more sense to have it called "Private group", since friends implies a two-way relationship

**Describe the solution you'd like**
Rename where we use friends to use "Private group"

**Additional context**
This is from a conversation with Mena

**Comment by MenaMachado** [comment]
Hi guys, I was speaking with Ali, and he suggested calling them "connections", which I like. So basically we are adding connections to our private group.

**Comment by MenaMachado** [comment]
Perhaps, the Heading is called Private Group but the subheading "Connections"

![image](https://user-images.githubusercontent.com/49656364/86970847-1bfe3880-c13e-11ea-99b8-8bcd1683e58e.png)

**Comment by MenaMachado** [comment]
For the privacy button, instead of "friends only", can you change it to "private group only". It implies the entire group of connections can see the info.  You may have already thought of this, we should change "Add Friend" to "Add connection". Connection needs to be lower case. 
![image](https://user-images.githubusercontent.com/49656364/86974884-16582100-c145-11ea-9fef-9dd667e4d5c0.png)
