### ISSUE TITLE
Add privacy buttons to every card on Edit Profile Page

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#495]
**Is your feature request related to a problem? Please describe.**
When a user first creates their profile, there's no indication on whether the information they are entering will be kept private or public, unless they go through the privacy statements or FAQs beforehand. 

**Describe the solution you'd like**
We should add the privacy buttons on the Edit profile page so that new users can set up their privacy settings as they create their profile.  This way, they can edit their privacy settings from the Edit page as well. 

**Additional context**
![image](https://user-images.githubusercontent.com/49656364/86978563-3390ed80-c14d-11ea-808b-15e0f0937009.png)

![image](https://user-images.githubusercontent.com/49656364/86978467-ffb5c800-c14c-11ea-9ec2-201690f3820d.png)

**Comment by BenJeau** [comment]
I think a potential problem here is that the forms are not linked to a single card in the profile view, but rather multiple cards. So per form there would be multiple privacy toggles which may be tricky for the user to know which toggle do what, but I think implemented correctly, it should be fine. But it wouldn't be as simple as adding a toggle per form. If ever you still want this, I have an idea on how it could look and I can quickly make a mockup

**Comment by MenaMachado** [comment]
Good point, I just noticed the Sections within the Edit page are not set up as the Profile view.  If you have an idea on how we can do it from Edit page, that would be great.

**Comment by BenJeau** [comment]
Here are some mockups, the little i besides job mobility would be present for sections where it would be present in multiple forms, telling the user that the toggle applies also for X and X part. Maybe instead of an i, it should be a ?

Let me know which one you like the best

1. 
![Web 1920 – 1@2x](https://user-images.githubusercontent.com/22248828/87090753-74007200-c206-11ea-9af6-f01bfd408d36.png)
2.
![Web 1920 – 2@2x](https://user-images.githubusercontent.com/22248828/87090777-84185180-c206-11ea-9e3e-a31e5493e3f2.png)
3. 
![Web 1920 – 3@2x](https://user-images.githubusercontent.com/22248828/87090796-8aa6c900-c206-11ea-8bcd-cab120bc0115.png)
![Web 1920 – 4@2x](https://user-images.githubusercontent.com/22248828/87090799-8bd7f600-c206-11ea-8670-e161307bd50a.png)
4. 
![Web 1920 – 5@2x](https://user-images.githubusercontent.com/22248828/87090803-8ed2e680-c206-11ea-85ec-a4c759e7112c.png)

**Comment by BenJeau** [comment]
After discussing with Mena, she likes the second option the best
