### ISSUE TITLE
Clean up frontend routes 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#521]
Right now we have very long routes that are going to get messy as the app grows. I propose we change to the following routes:

domain.com => home 
domain.com/login =>login
domain.com/profile/:id =>profile 
domain.com/admin => admin 

I think we should try to keep the domains as short as possible since users might want to share them with others having a very long domain might be difficult. If anyone has any opinions on this please feel free to comment. 

relates to: #248

**Comment by BenJeau** [comment]
In addition, to cleaning up the routes, we should handle keycloak.js correctly (not request a new access token on every page load, just use existing access token until it expires and update it via the refresh token ONLY when the access token is not good). Not sure if this should be a separate issue.

**Comment by BenJeau** [comment]
Since we are only injecting the keycloak access token in `/secured` and `/admin` routes, the access token is not available in `/`. The API call should still be able to get through since I am logged in
![Peek 2020-07-14 09-53](https://user-images.githubusercontent.com/22248828/87436065-8ab61880-c5ba-11ea-979a-6d46dc72aeb7.gif)
