### ISSUE TITLE
Add an alert message for users to save their unsaved changes made to their profile

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#576]
**Is your feature request related to a problem? Please describe.**
When users edit sections of their profile, they can forget to click on the save and finish button before leaving that section. 

This issue is connected to issue: 509
https://github.com/CDH-Studio/UpSkill/issues/509

**Describe the solution you'd like**
If a user doesn't click on the save and finish button, the moment they click on something outside the applicable card, they should be prompted with a warning message that says the following: 

- Do you want to save the changes to to save changes? (yes, no, cancel)

When the save is sucessful, they should receive a message saying:
- Successfully saved with the green checkmark

![image](https://user-images.githubusercontent.com/49656364/88330084-decaa680-ccf8-11ea-855b-2cd5a433a460.png)

**Comment by BenJeau** [comment]
In order to get the prompt to actually save, we would need to implement #448 (since the prompt is "outside" of the profile form, so its logic to make calls to the backend should also be extracted from the components, and be put in something central like `redux-thunk`). Meanwhile, I've implemented a simple prompt that just alerts the user if the form has unsaved changes and blocks them from going to the next page.

**Comment by MenaMachado** [comment]
Perfect
