### ISSUE TITLE
Invalid prop "LoadingComponent" supplied to KeycloakProvider

### ISSUE THREAD

**Issue by SukhsimranpreetSekhon** [CDH-Studio/I-Talent#871]
**Describe the bug**
Warning error describing that the prop "LoadingComponent" of type "function" is supplied to the "KeycloakProvider", when it was expecting a single ReactElement.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Main Page of the Web Application.
2. Click on Chrome Dev Tools.
3. It is apart of the first and second error message.

**Expected behaviour**
Need error to not show up for the launch.

**Screenshots**
![Invalid prop for Keycloak](https://user-images.githubusercontent.com/35780281/93232750-437a0e80-f748-11ea-8c4d-a1c8af343b19.jpg)

**Additional context**

**Comment by BenJeau** [comment]
This prop error is a complicated one. 

It's related to this line https://github.com/CDH-Studio/UpSkill/blob/development/services/frontend-v3/src/client.jsx#L16. What that prop wants to receive is just a component, so it would be `<AppLayout loading />` instead of `() => <AppLayout loading />`, but making that change will break the app since the component `AppLayout` makes references to `redux` and `react-intl` which the providers for those packages have not yet been initialized at that point... 

You could try:
1. Moving the `<AppProvider />` before the `<SSRKeycloakProvider />`, but I think that opens new problems... not sure though, I just followed this example for the `@react-keycloak/razzle` package https://www.npmjs.com/package/@react-keycloak/razzle#getting-started

OR

2. Create a component specifically used when loading keycloak
